"""Conformance suite for the open verifier.

GENERATED by `tools/export_public_os.py` in the source repo -- edit it there.

This is not a smoke test. It runs the same suite the wheel's own acceptance test runs,
against the vectors shipped inside the package, and asserts the two properties that
make the verifier worth installing: every forgery is rejected FOR ITS OWN STATED
REASON, and no genuine envelope degrades for any reason other than a substrate the
installing machine does not have.
"""

from alelyon.verify.conformance import run_conformance


def test_the_package_ships_its_own_vectors():
    r = run_conformance()
    assert r["total"] > 0, "no conformance vectors inside the installed package"
    assert r["forgeries"] > 0 and r["goldens"] > 0


def test_every_vector_reaches_its_declared_verdict():
    r = run_conformance()
    bad = [c for c in r["results"] if c["status"] not in ("pass", "skip")]
    assert not bad, "\n".join(
        f"{c['slug']}: {c.get('reason') or c.get('mismatches')}" for c in bad)
    assert r["failed"] == 0


def test_no_forgery_verifies_and_each_fails_for_its_own_reason():
    """The property that makes the verifier worth installing.

    `failed == 0` alone would pass if a case declared no expected reason, so this
    asserts the shape directly: nothing marked must-fail came back ok, and every one
    named at least one reason class.
    """
    r = run_conformance()
    forgeries = [c for c in r["results"] if c["category"] == "forgery"]
    assert len(forgeries) == r["forgeries"]
    for c in forgeries:
        assert c["must"] == "fail"
        assert c["actual"]["ok"] is False, f"{c['slug']} VERIFIED"
        assert c["actual"]["reason_classes"], f"{c['slug']} rejected with no reason"


def test_goldens_verify_or_say_which_substrate_they_needed():
    """Without the deterministic kernel a width cannot be re-derived (SPEC 8.1).

    That is the ONLY excuse a genuine envelope has for not verifying here, so this
    asserts on `substrate` rather than letting any degradation pass.
    """
    r = run_conformance()
    goldens = [c for c in r["results"] if c["category"] == "golden"]
    if r["substrate_specified"]:
        assert r["goldens_verified"] == r["goldens"], f"kernel: {r['kernel']}"
    for c in goldens:
        if not c["actual"]["ok"]:
            assert c["substrate"] != "matched", (
                f"{c['slug']} failed on a MATCHING substrate: "
                f"{c['actual']['reason_classes']}")
