"""Fail-closed boundary tests for the open verifier.

GENERATED by `tools/export_public_os.py` in the source repo -- edit it there.

These tests use only the public package and its declared test dependencies.  They
cover malformed/resource-hostile JSON and signed-envelope replay inputs separately:
passing the bundled conformance vectors alone is not evidence that either raw-input
boundary is bounded or unambiguous.
"""

from __future__ import annotations

import copy
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

import alelyon
from alelyon.runtime.atlas.data.attest import KeyStore, canonical, payload_deltas
from alelyon.runtime.oracle.dsl.envelope import (
    MalformedEnvelope,
    _decompress_deltas,
    _unsigned,
    build_envelope,
)
import alelyon.runtime.oracle.dsl.execcert as execcert
from alelyon.runtime.oracle.dsl.parser import (
    MAX_DSL_AST_DEPTH,
    MAX_DSL_AST_NODES,
    MAX_DSL_SOURCE_BYTES,
    MAX_DSL_TOKENS,
)
from alelyon.runtime.oracle.dsl.verify import verify_envelope
from alelyon.verify import cli


PROGRAM = 'show mean(price("SYN"))'


class _Fetcher:
    def __init__(self, series, delta):
        self.series = series
        self.delta = delta

    def get(self, kind, key):
        assert (kind, key) == ("price", "SYN")
        return execcert.FetchedSeries(
            series=self.series.copy(),
            deltas=np.full(len(self.series), self.delta, dtype=float),
            uncertified=0,
        )


@pytest.fixture(scope="module")
def signed_case(tmp_path_factory):
    series = pd.Series(
        [100.0, 101.0, 102.0, 103.0],
        index=pd.date_range("2024-01-02", periods=4),
        name="SYN",
    )
    keystore = KeyStore(key_dir=str(tmp_path_factory.mktemp("keys")))
    envelope = build_envelope(
        PROGRAM,
        fetcher=_Fetcher(series, 0.0),
        keystore=keystore,
        seed=7,
        now=1000.0,
    )
    baseline = verify_envelope(
        envelope,
        {("price", "SYN"): series},
        public_key_hex=keystore.public_key_hex(),
    )
    assert baseline["ok"] is True, baseline
    return envelope, series, keystore


def _resign(envelope, keystore):
    envelope["signature"] = keystore.sign(canonical(_unsigned(envelope))).hex()


def test_imports_resolve_to_the_generated_public_tree():
    package_root = Path(__file__).resolve().parents[1]
    assert Path(alelyon.__file__).resolve().is_relative_to(package_root)


@pytest.mark.parametrize("raw", [
    '{"a": 1, "a": 2}',
    r'{"a": 1, "\u0061": 2}',
    '{"outer": {"a": 1, "a": 2}}',
    '{"value": NaN}',
    '{"value": 1e9999}',
    '{"value": ' + ("1" * 1025) + '}',
])
def test_cli_rejects_ambiguous_nonfinite_or_oversized_numbers(tmp_path, raw):
    path = tmp_path / "input.json"
    path.write_text(raw, encoding="utf-8")
    with pytest.raises(ValueError):
        cli._load_json(str(path))


def test_cli_reports_malformed_json_as_usage_error(tmp_path, capsys):
    path = tmp_path / "duplicate.json"
    path.write_text('{"a": 1, "a": 2}', encoding="utf-8")
    assert cli.main(["verify", "--envelope", str(path)]) == 2
    assert "cannot read input" in capsys.readouterr().err


@pytest.mark.parametrize("encoding", ["utf-16", "utf-32"])
def test_cli_rejects_non_utf8_before_structural_validation(tmp_path, encoding):
    path = tmp_path / "alternate-encoding.json"
    path.write_bytes('{"value": [0]}'.encode(encoding))
    with pytest.raises(ValueError, match="UTF-8"):
        cli._load_json(str(path))


def test_cli_file_depth_and_structural_resource_limits(tmp_path, monkeypatch):
    assert cli._MAX_JSON_FILE_BYTES == 64 * 1024 * 1024
    assert cli._MAX_JSON_DEPTH == 64

    path = tmp_path / "bounded.json"
    path.write_bytes(b"[0, 0, 0]")
    monkeypatch.setattr(cli, "_MAX_JSON_FILE_BYTES", 4)
    with pytest.raises(ValueError, match="exceeds"):
        cli._load_json(str(path))

    monkeypatch.setattr(cli, "_MAX_JSON_FILE_BYTES", 1024)
    path.write_text("[" * 65 + "0" + "]" * 65, encoding="utf-8")
    with pytest.raises(ValueError, match="nesting"):
        cli._load_json(str(path))

    path.write_text("[0, 0, 0]", encoding="utf-8")
    monkeypatch.setattr(cli, "_MAX_JSON_NODES", 3)
    with pytest.raises(ValueError, match="node limit"):
        cli._load_json(str(path))

    monkeypatch.setattr(cli, "_MAX_JSON_NODES", 2_000_000)
    monkeypatch.setattr(cli, "_MAX_JSON_CONTAINER_ITEMS", 2)
    with pytest.raises(ValueError, match="item limit"):
        cli._load_json(str(path))

    monkeypatch.setattr(cli, "_MAX_JSON_CONTAINER_ITEMS", 1_000_000)
    monkeypatch.setattr(cli, "_MAX_JSON_STRING_BYTES", 3)
    path.write_text('"four"', encoding="utf-8")
    with pytest.raises(ValueError, match="string limit"):
        cli._load_json(str(path))


@pytest.mark.parametrize("encoding", ["utf-16", "utf-32"])
def test_capture_payload_non_utf8_yields_no_claim(encoding):
    payload = '[{"column":"close","delta":0.1}]'.encode(encoding)
    assert payload_deltas(payload) == ({}, [])


def test_a_well_formed_delta_block_still_decodes():
    got = _decompress_deltas(
        {"const": 0.25, "n": 2, "uncertified_idx": [1]}
    )
    assert got[0] == 0.25
    assert np.isnan(got[1])


@pytest.mark.parametrize("block", [
    {"const": 0.1, "runs": [[0.1, 1]], "n": 1, "uncertified_idx": []},
    {"const": 0.1, "n": 1},
    {"const": 0.1, "n": "1", "uncertified_idx": []},
    {"const": 0.1, "n": True, "uncertified_idx": []},
    {"const": 0.1, "n": 1, "uncertified_idx": [0.0]},
    {"runs": [[0.1, 1.0]], "n": 1},
    {"const": -0.1, "n": 1, "uncertified_idx": []},
    {"const": None, "n": 1, "uncertified_idx": []},
    {"list": [False]},
    {"list": ["0.1"]},
    {"list": [float("inf")]},
])
def test_delta_blocks_refuse_ambiguous_types_and_values(block):
    with pytest.raises(MalformedEnvelope):
        _decompress_deltas(block)


@pytest.mark.parametrize("seed", [-1, 1.0, True, 1 << 64])
def test_signed_replay_seed_requires_an_unsigned_u64(signed_case, seed):
    original, series, keystore = signed_case
    envelope = copy.deepcopy(original)
    envelope["seed"] = seed
    _resign(envelope, keystore)
    result = verify_envelope(
        envelope,
        {("price", "SYN"): series},
        public_key_hex=keystore.public_key_hex(),
    )
    assert result["ok"] is False
    assert "malformed-envelope" in result["reason_classes"]


def test_signed_replay_params_must_be_an_object(signed_case):
    original, series, keystore = signed_case
    envelope = copy.deepcopy(original)
    envelope["params"] = []
    _resign(envelope, keystore)
    result = verify_envelope(
        envelope,
        {("price", "SYN"): series},
        public_key_hex=keystore.public_key_hex(),
    )
    assert "malformed-envelope" in result["reason_classes"]


@pytest.mark.parametrize(("field", "value"), [
    ("K", -1),
    ("K", 1.0),
    ("K", True),
    ("K", "63"),
    ("K", 1 << 64),
    ("alpha", True),
    ("alpha", "0.05"),
    ("strict", 1),
    ("strict", "false"),
    ("require_tier", None),
    ("require_tier", 1),
])
def test_signed_replay_params_preserve_json_types(signed_case, field, value):
    original, series, keystore = signed_case
    envelope = copy.deepcopy(original)
    envelope["params"][field] = value
    _resign(envelope, keystore)
    result = verify_envelope(
        envelope,
        {("price", "SYN"): series},
        public_key_hex=keystore.public_key_hex(),
    )
    assert result["ok"] is False
    assert "malformed-envelope" in result["reason_classes"]


def _unexpected_rng(*args, **kwargs):
    raise AssertionError("resource refusal must happen before resampling")


def test_resample_count_refuses_before_rng_work(monkeypatch):
    monkeypatch.setattr(execcert.np.random, "default_rng", _unexpected_rng)
    series = pd.Series(
        np.arange(4, dtype=float),
        index=pd.date_range("2024-01-02", periods=4),
        name="SYN",
    )
    cert = execcert.certified_run(
        PROGRAM,
        fetcher=_Fetcher(series, 1e-4),
        K=execcert.MAX_REPLAY_RESAMPLES + 1,
        seed=1,
    )
    assert cert.refused is True
    assert cert.reason == "K=10001 exceeds the verifier limit of 10000 resamples"


def test_aggregate_replay_work_refuses_before_rng_work(monkeypatch):
    monkeypatch.setattr(execcert.np.random, "default_rng", _unexpected_rng)
    series = pd.Series(
        np.arange(120, dtype=float),
        index=pd.date_range("2024-01-02", periods=120),
        name="SYN",
    )
    term = 'mean(price("SYN"))'
    cert = execcert.certified_run(
        "show " + " + ".join([term] * 15),
        fetcher=_Fetcher(series, 1e-4),
        K=execcert.MAX_REPLAY_RESAMPLES,
        seed=1,
    )
    assert cert.refused is True
    assert cert.reason == (
        "replay work 72007200 exceeds the verifier limit of 50000000 units "
        "(rows=120, K=10000, AST nodes=60)"
    )


def test_profile1_resource_policy_constants_are_frozen():
    assert (
        MAX_DSL_SOURCE_BYTES,
        MAX_DSL_TOKENS,
        MAX_DSL_AST_NODES,
        MAX_DSL_AST_DEPTH,
        execcert.MAX_REPLAY_RESAMPLES,
        execcert.MAX_REPLAY_WORK_UNITS,
    ) == (65_536, 16_384, 8_192, 64, 10_000, 50_000_000)


@pytest.mark.parametrize(("program", "limit_name", "limit"), [
    ("x" * (MAX_DSL_SOURCE_BYTES + 1), "byte", MAX_DSL_SOURCE_BYTES),
    (";".join(["show 0"] * (MAX_DSL_TOKENS // 3 + 1)),
     "token", MAX_DSL_TOKENS),
    (";".join(["show 0"] * (MAX_DSL_AST_NODES // 2 + 1)),
     "AST node", MAX_DSL_AST_NODES),
    ("show " + "(" * MAX_DSL_AST_DEPTH + "0" + ")" * MAX_DSL_AST_DEPTH,
     "AST depth", MAX_DSL_AST_DEPTH),
], ids=["source-bytes", "tokens", "ast-nodes", "ast-depth"])
def test_dsl_resource_limits_refuse_without_recursion(program, limit_name, limit):
    cert = execcert.certified_run(program, seed=1)
    assert cert.refused is True
    assert f"program exceeds DSL {limit_name} limit of {limit}" in cert.reason
    assert "recursion" not in cert.reason.lower()
