"""Lattice — deterministic exact coordinate registration foundations.

The current surface is immutable coordinate contracts, exact target-to-source
transforms with a declared loss/invertibility surface, compatibility refusals, a
canonical byte encoding with content commitments, a replay checker that recovers
a committed chain from those bytes and re-executes it, and a signed Registration
Certificate for an exact correspondence.

The certificate populates 13 of the specification's 34 fields and carries the
other 21 as named absences inside its signed bytes. It does not read payloads,
remap values, propagate uncertainty, or claim optimality, and a signature binds
bytes to a key rather than establishing who holds it. See
`docs/architecture/adr/ADR-0001-lattice-foundation.md`, `ADR-0002` and `ADR-0004`
for the frozen boundary.
"""

from alelyon.runtime.vector.lattice.canonical import (
    CANONICAL_SCHEMA,
    CanonicalEncodingError,
    axis_bytes,
    coordinate_space_bytes,
    coordinate_space_ref,
    read_coordinate_space,
    read_transform_chain,
    transform_bytes,
    transform_chain_bytes,
    transform_chain_ref,
    transform_ref,
)
from alelyon.runtime.vector.lattice.certificate import (
    CERTIFICATE_SCHEMA,
    DECLARED_ABSENCES,
    SPEC_CERTIFICATE_FIELDS,
    CertificateCode,
    CertificateError,
    CertificateReport,
    CertificateSignature,
    DeterminismProfile,
    FieldAbsence,
    FieldStatus,
    RegistrationCertificate,
    SignedRegistrationCertificate,
    certificate_bytes,
    certificate_ref,
    issue_registration_certificate,
    read_certificate,
    verify_registration_certificate,
)
from alelyon.runtime.vector.lattice.contracts import (
    AxisKind,
    CoordinateAxis,
    CoordinateOrdering,
    CoordinateSpace,
    LABEL_DICTIONARY_SCHEMA,
    MAX_SPACE_ENCODED_BYTES,
    Periodicity,
    ScalarType,
    TopologyType,
    label_dictionary_ref,
)
from alelyon.runtime.vector.lattice.morphometry import (
    Cell,
    FAMILIES,
    MODULES,
    ModelMorphometry,
    TensorRecord,
    Voxel,
    VoxelField,
    analyze as analyze_model_morphometry,
    canonical_space as morphometry_canonical_space,
    certify as certify_model_morphometry,
    register as register_model_morphometry,
    space_commitment as morphometry_space_commitment,
    voxel_field,
)
from alelyon.runtime.vector.lattice.registration import (
    CompatibilityCode,
    CompatibilityReport,
    DeclaredLabelReindex,
    DeclaredCalendarAlias,
    DeclaredOrientationFlip,
    DeclaredReferenceShift,
    DeclaredTimezoneConversion,
    DeclaredUnitConversion,
    analyze_exact_compatibility,
)
from alelyon.runtime.vector.lattice.transforms import (
    AxisOrderingTransform,
    AxisOrientationTransform,
    AxisReferenceShift,
    AxisPermutationTransform,
    AxisTimezoneOffset,
    AxisUnitConversion,
    CalendarTransform,
    IdentityTransform,
    Invertibility,
    LabelReindexTransform,
    LossClass,
    ReferenceBasisTransform,
    TimezoneTransform,
    TransformChain,
    TransformDirection,
    UnitAffineTransform,
)
from alelyon.runtime.vector.lattice.verify import (
    ReplayCode,
    ReplayReport,
    chain_commitment,
    verify_transform_chain,
)

__all__ = [
    "AxisKind",
    "AxisOrderingTransform",
    "AxisOrientationTransform",
    "AxisReferenceShift",
    "AxisPermutationTransform",
    "AxisTimezoneOffset",
    "AxisUnitConversion",
    "CalendarTransform",
    "CANONICAL_SCHEMA",
    "CERTIFICATE_SCHEMA",
    "CanonicalEncodingError",
    "Cell",
    "CertificateCode",
    "CertificateError",
    "CertificateReport",
    "CertificateSignature",
    "CompatibilityCode",
    "CompatibilityReport",
    "CoordinateAxis",
    "CoordinateOrdering",
    "CoordinateSpace",
    "DECLARED_ABSENCES",
    "DeclaredLabelReindex",
    "DeclaredCalendarAlias",
    "DeclaredOrientationFlip",
    "DeclaredReferenceShift",
    "DeclaredTimezoneConversion",
    "DeclaredUnitConversion",
    "DeterminismProfile",
    "FAMILIES",
    "FieldAbsence",
    "FieldStatus",
    "IdentityTransform",
    "Invertibility",
    "LABEL_DICTIONARY_SCHEMA",
    "LabelReindexTransform",
    "ReferenceBasisTransform",
    "LossClass",
    "MAX_SPACE_ENCODED_BYTES",
    "MODULES",
    "ModelMorphometry",
    "Periodicity",
    "RegistrationCertificate",
    "ReplayCode",
    "ReplayReport",
    "SPEC_CERTIFICATE_FIELDS",
    "ScalarType",
    "SignedRegistrationCertificate",
    "TensorRecord",
    "TimezoneTransform",
    "TopologyType",
    "TransformChain",
    "TransformDirection",
    "UnitAffineTransform",
    "Voxel",
    "VoxelField",
    "analyze_exact_compatibility",
    "analyze_model_morphometry",
    "axis_bytes",
    "certificate_bytes",
    "certify_model_morphometry",
    "certificate_ref",
    "chain_commitment",
    "coordinate_space_bytes",
    "coordinate_space_ref",
    "issue_registration_certificate",
    "label_dictionary_ref",
    "morphometry_canonical_space",
    "morphometry_space_commitment",
    "read_certificate",
    "read_coordinate_space",
    "read_transform_chain",
    "register_model_morphometry",
    "transform_bytes",
    "transform_chain_bytes",
    "transform_chain_ref",
    "transform_ref",
    "verify_registration_certificate",
    "verify_transform_chain",
    "voxel_field",
]
