"""Lattice — deterministic exact coordinate registration foundations.

The current surface is immutable coordinate contracts, exact target-to-source
transforms with a declared loss/invertibility surface, compatibility refusals, a
canonical byte encoding with content commitments, a replay checker that recovers
a committed chain from those bytes and re-executes it, and a signed Registration
Certificate for an exact correspondence.

The certificate populates 15 of the specification's 34 fields and carries the
other 19 as named absences inside its signed bytes. It does not read payloads,
remap values, propagate uncertainty, or claim optimality, and a signature binds
bytes to a key rather than establishing who holds it. Its measured bounds are
`inverse_consistency`, a count over a derived probe sample rather than a proof
that the chain inverts everywhere, and `execution_trace_commitment`, which binds
that count to the probe executions it tallies. Verification additionally re-runs
the registration ladder, so a chain registration would never have emitted is
refused even when it replays cleanly. See
`docs/architecture/adr/ADR-0001-lattice-foundation.md`, `ADR-0002`, `ADR-0004`,
`ADR-0018` and `ADR-0019` for the frozen boundary.
"""

from alelyon.runtime.vector.lattice.canonical import (
    CANONICAL_SCHEMA,
    CanonicalEncodingError,
    ContractViolationError,
    artifact_manifest_bytes,
    artifact_manifest_ref,
    axis_bytes,
    canonical_template_bytes,
    canonical_template_ref,
    coordinate_space_bytes,
    coordinate_space_ref,
    read_artifact_manifest,
    read_canonical_template,
    read_coordinate_space,
    read_transform_chain,
    transform_bytes,
    transform_chain_bytes,
    transform_chain_ref,
    transform_ref,
)
from alelyon.runtime.vector.lattice.certificate import (
    CERTIFICATE_SCHEMA,
    DECLARED_ABSENCES,
    SPEC_CERTIFICATE_FIELDS,
    CertificateCode,
    CertificateError,
    CertificateReport,
    CertificateSignature,
    DeterminismProfile,
    FieldAbsence,
    FieldStatus,
    RegistrationCertificate,
    SignedRegistrationCertificate,
    certificate_bytes,
    certificate_ref,
    issue_registration_certificate,
    read_certificate,
    verify_registration_certificate,
)
from alelyon.runtime.vector.lattice.inheritance import (
    AXIS_FIELD_CLASSES,
    AXIS_IDENTITY_FIELDS,
    SPACE_FIELD_CLASSES,
    SPACE_IDENTITY_FIELDS,
    FieldClass,
    InheritanceFinding,
    InheritanceReport,
    compare_axes,
    compare_spaces,
    uncompared_semantics,
)
from alelyon.runtime.vector.lattice.manifest import (
    ARTIFACT_MANIFEST_SCHEMA,
    MAX_DECLARED_CELLS,
    NON_INTERPOLABLE_SEMANTICS,
    ArtifactManifest,
    AxisExtent,
    ManifestGaps,
    ManifestValidationError,
    MissingnessState,
    UncertaintyModel,
    ValueSemantics,
    declared_extent,
    manifests_share_shape,
    validate_extents,
)
from alelyon.runtime.vector.lattice.template import (
    CANONICAL_TEMPLATE_SCHEMA,
    KNOWN_TRANSFORM_TYPES,
    TEMPLATE_TIER_ORDER,
    CanonicalTemplate,
    CreationMethod,
    TemplateRegistry,
    TemplateTier,
    TemplateValidationError,
    narrows_parent,
)
from alelyon.runtime.vector.lattice.contracts import (
    AxisKind,
    CoordinateAxis,
    CoordinateOrdering,
    CoordinateSpace,
    LABEL_DICTIONARY_SCHEMA,
    MAX_SPACE_ENCODED_BYTES,
    Periodicity,
    ScalarType,
    TopologyType,
    label_dictionary_ref,
)
from alelyon.runtime.vector.lattice.inverse import (
    MAX_PROBES,
    InverseConsistency,
    InverseConsistencyCode,
    derive_probe_coordinates,
    measure_inverse_consistency,
)
from alelyon.runtime.vector.lattice.morphometry import (
    Cell,
    FAMILIES,
    MODULES,
    ModelMorphometry,
    TensorRecord,
    Voxel,
    VoxelField,
    analyze as analyze_model_morphometry,
    canonical_space as morphometry_canonical_space,
    certify as certify_model_morphometry,
    register as register_model_morphometry,
    space_commitment as morphometry_space_commitment,
    voxel_field,
)
from alelyon.runtime.vector.lattice.registration import (
    CompatibilityCode,
    CompatibilityReport,
    DeclaredLabelReindex,
    DeclaredCalendarAlias,
    DeclaredOrientationFlip,
    DeclaredReferenceShift,
    DeclaredTimezoneConversion,
    DeclaredUnitConversion,
    RegistrationDeclarations,
    analyze_exact_compatibility,
)
from alelyon.runtime.vector.lattice.timezone_audit import (
    TimezoneAuditFinding,
    TimezoneAuditReport,
    TimezoneAuditVerdict,
    audit_declared_conversion,
    audit_timezone_transform,
)
from alelyon.runtime.vector.lattice.transforms import (
    AxisOrderingTransform,
    AxisOrientationTransform,
    AxisReferenceShift,
    AxisPermutationTransform,
    AxisTimezoneOffset,
    AxisUnitConversion,
    CalendarTransform,
    IdentityTransform,
    Invertibility,
    LabelReindexTransform,
    LossClass,
    ReferenceBasisTransform,
    TimezoneTransform,
    TransformChain,
    TransformDirection,
    UnitAffineTransform,
)
from alelyon.runtime.vector.lattice.verify import (
    ReplayCode,
    ReplayReport,
    chain_commitment,
    verify_transform_chain,
)

__all__ = [
    "ARTIFACT_MANIFEST_SCHEMA",
    "AXIS_FIELD_CLASSES",
    "AXIS_IDENTITY_FIELDS",
    "ArtifactManifest",
    "AxisExtent",
    "AxisKind",
    "AxisOrderingTransform",
    "AxisOrientationTransform",
    "AxisPermutationTransform",
    "AxisReferenceShift",
    "AxisTimezoneOffset",
    "AxisUnitConversion",
    "CANONICAL_SCHEMA",
    "CANONICAL_TEMPLATE_SCHEMA",
    "CERTIFICATE_SCHEMA",
    "InverseConsistency",
    "InverseConsistencyCode",
    "MAX_PROBES",
    "derive_probe_coordinates",
    "measure_inverse_consistency",
    "CanonicalEncodingError",
    "CanonicalTemplate",
    "Cell",
    "CertificateCode",
    "CertificateError",
    "CertificateReport",
    "CertificateSignature",
    "CompatibilityCode",
    "CompatibilityReport",
    "ContractViolationError",
    "CoordinateAxis",
    "CoordinateOrdering",
    "CoordinateSpace",
    "CreationMethod",
    "DECLARED_ABSENCES",
    "DeclaredCalendarAlias",
    "DeclaredLabelReindex",
    "DeclaredOrientationFlip",
    "DeclaredReferenceShift",
    "DeclaredTimezoneConversion",
    "DeclaredUnitConversion",
    "DeterminismProfile",
    "FAMILIES",
    "FieldAbsence",
    "FieldClass",
    "FieldStatus",
    "IdentityTransform",
    "InheritanceFinding",
    "InheritanceReport",
    "Invertibility",
    "KNOWN_TRANSFORM_TYPES",
    "LABEL_DICTIONARY_SCHEMA",
    "LabelReindexTransform",
    "LossClass",
    "MAX_DECLARED_CELLS",
    "MAX_SPACE_ENCODED_BYTES",
    "MODULES",
    "ManifestGaps",
    "ManifestValidationError",
    "MissingnessState",
    "ModelMorphometry",
    "NON_INTERPOLABLE_SEMANTICS",
    "Periodicity",
    "ReferenceBasisTransform",
    "RegistrationCertificate",
    "RegistrationDeclarations",
    "ReplayCode",
    "ReplayReport",
    "SPACE_FIELD_CLASSES",
    "SPACE_IDENTITY_FIELDS",
    "SPEC_CERTIFICATE_FIELDS",
    "ScalarType",
    "SignedRegistrationCertificate",
    "TEMPLATE_TIER_ORDER",
    "TemplateRegistry",
    "TemplateTier",
    "TemplateValidationError",
    "TensorRecord",
    "TimezoneAuditFinding",
    "TimezoneAuditReport",
    "TimezoneAuditVerdict",
    "TimezoneTransform",
    "TopologyType",
    "TransformChain",
    "TransformDirection",
    "UncertaintyModel",
    "UnitAffineTransform",
    "ValueSemantics",
    "Voxel",
    "VoxelField",
    "analyze_exact_compatibility",
    "analyze_model_morphometry",
    "artifact_manifest_bytes",
    "artifact_manifest_ref",
    "audit_declared_conversion",
    "audit_timezone_transform",
    "axis_bytes",
    "canonical_template_bytes",
    "canonical_template_ref",
    "certificate_bytes",
    "certificate_ref",
    "certify_model_morphometry",
    "chain_commitment",
    "compare_axes",
    "compare_spaces",
    "coordinate_space_bytes",
    "coordinate_space_ref",
    "declared_extent",
    "issue_registration_certificate",
    "label_dictionary_ref",
    "manifests_share_shape",
    "morphometry_canonical_space",
    "morphometry_space_commitment",
    "narrows_parent",
    "read_artifact_manifest",
    "read_canonical_template",
    "read_certificate",
    "read_coordinate_space",
    "read_transform_chain",
    "register_model_morphometry",
    "transform_bytes",
    "transform_chain_bytes",
    "transform_chain_ref",
    "transform_ref",
    "uncompared_semantics",
    "validate_extents",
    "verify_registration_certificate",
    "verify_transform_chain",
    "voxel_field",
]
