"""Conformance runner for the language-neutral CNE test-vector suite (Track 0, W5).

The adversarial cases for the CNE format used to exist only as pytest code, which
made them Python-bound: a second-language implementation could not consume them,
and neither could an external party checking our claims. This module runs the
JSON vector suite instead — the same files a Rust or TypeScript verifier reads.

    from alelyon.verify import run_conformance
    report = run_conformance()
    assert report["failed"] == 0

Contract, per SPEC-cne-v0.md §0.2: a case passes iff the verifier reproduces the
recorded `ok`, EVERY `checks` slot including its nulls, the `width_trust` and
`provider_trust` labels, and the exact SET of `reason_classes`. Prose reasons are
deliberately not compared — they are for humans and may be reworded.

Substrate handling (SPEC §8.1). A width reproduces bit-for-bit only on the kernel
that produced it, so every case records two expectations: `expect` for a verifier
whose kernel matches the envelope's, and `expect_off_substrate` for one whose does
not. A case with no expectation for the local substrate is reported SKIPPED with
its reason — never silently counted as a pass. `run_conformance` treats an
unexpected skip as a failure of the suite's coverage, not of the verifier, and
reports the two separately.

Import closure: this module is part of the open verifier and must stay free of the
capture engine, the store, and the GUI (tests/oracle/test_verifier_extractable.py
is the contract). The vectors are GENERATED by tools/gen_cne_vectors.py, which may
import anything it likes; nothing here does.
"""
from __future__ import annotations

import json
from typing import Dict, List, Optional

import pandas as pd

from alelyon.runtime.oracle.dsl.envelope import _kernel_id
from alelyon.runtime.oracle.dsl.verify import verify_envelope

#: The spec revision these vectors instantiate. A vector recorded against a
#: different spec version is a hard error, not a warning: the suite and the
#: document are versioned together (SPEC §10.3).
SPEC_VERSION = "alelyon.cne-spec/0.3.0"

_CHECK_SLOTS = ("authenticity", "inputs", "scalar", "width", "budget",
                "program", "tier", "transparency", "witness", "key_status",
                "provider")


def _provider_trust(verdict: dict):
    """Return the normative provider-trust label for a verdict/expectation.

    SPEC §9.6 defines this label entirely from ``checks.provider``. Older v0
    vector expectation blocks, and two verifier early-refusal paths, predate the
    redundant top-level field. Deriving it only when the field is absent lets
    those artifacts participate in parity without hiding an explicitly wrong
    label: an explicit value always wins and is compared verbatim.
    """
    if "provider_trust" in verdict:
        return verdict.get("provider_trust")
    checks = verdict.get("checks") or {}
    return ("transparency-anchored" if checks.get("provider") is True
            else "signer-attested")


def vectors_path():
    """The bundled vector directory, resolved through importlib.resources so it
    works identically from a source checkout and from an installed wheel."""
    from importlib.resources import files
    return files("alelyon.verify") / "vectors"


def load_vectors(path=None) -> List[dict]:
    """Every vector case, sorted by slug so a run's order is reproducible."""
    root = path if path is not None else vectors_path()
    cases = []
    for entry in sorted(p.name for p in root.iterdir()
                        if p.name.endswith(".json") and p.name != "manifest.json"):
        cases.append(json.loads((root / entry).read_text(encoding="utf-8")))
    return sorted(cases, key=lambda c: str(c.get("slug")))


def series_from(spec: dict) -> pd.Series:
    """Rebuild a pandas Series from a vector's language-neutral input encoding.

    Two shapes, distinguished by which member is present, because the two input
    families are digested differently and must not be confused (SPEC §3.2, §3.4):

        {"index": [epoch seconds...], "values": [...]}   a time series
        {"keys":  ["CLM-00001", ...], "values": [...]}   a keyed table

    A time-series index is reconstructed as UTC timestamps from float epoch seconds,
    the form `input_digest` packs. A keyed table keeps its keys as plain strings —
    deliberately NOT coerced to timestamps, which is what a single shared decoder
    would have done to `CLM-00001`.

    `null` in `values` becomes NaN; the digests pack NaN's fixed bit pattern, so a
    null round-trips exactly.
    """
    vals = [float("nan") if v is None else float(v) for v in spec["values"]]
    if "keys" in spec:
        keys = [str(k) for k in spec["keys"]]
        return pd.Series(vals, index=keys, name=spec.get("name"))
    idx = pd.to_datetime([float(t) for t in spec["index"]], unit="s", utc=True)
    return pd.Series(vals, index=idx, name=spec.get("name"))


def _input_data(case: dict) -> Dict:
    """The `{(kind, key): Series}` map a case's envelope is verified against."""
    out: Dict = {}
    for k, spec in (case.get("inputs") or {}).items():
        kind, _, key = str(k).partition("|")
        out[(kind, key)] = series_from(spec)
    return out


def _expectation(case: dict, local_kernel: str):
    """(expectation, on_substrate, skip_reason). Picks `expect` when the local
    substrate matches the envelope's declared kernel, `expect_off_substrate`
    otherwise."""
    declared = (case.get("envelope") or {}).get("kernel")
    on_substrate = (declared == local_kernel)
    if on_substrate:
        exp = case.get("expect")
        if exp is None:
            return None, True, f"no `expect` recorded (substrate {local_kernel!r})"
        return exp, True, None
    exp = case.get("expect_off_substrate")
    if exp is None:
        return None, False, (
            f"envelope kernel {declared!r} differs from local {local_kernel!r} "
            f"and no `expect_off_substrate` is recorded")
    return exp, False, None


def _category_invariants(category: str, on_substrate: bool,
                         actual: dict) -> List[str]:
    """The properties each category asserts INDEPENDENTLY of any recorded
    expectation, so a mis-generated vector cannot invert the thing it exists to
    prove.

    The substrate axis matters here and is easy to get wrong. A **forgery must
    never verify on any substrate** — that is the release-blocking property and it
    is substrate-independent. A **golden verifies only on the substrate that
    produced it**: a width is a near-cancellation quantity that reproduces
    bit-for-bit on one kernel (SPEC §8.1), and `ok` requires the width to have been
    reproduced, so off-substrate a golden is *expected* to degrade. What it may not
    do is degrade for some OTHER reason — that would hide a real defect behind a
    substrate excuse — so off-substrate we require either a clean verify (refusals,
    whose bound was never claimed) or an honest `substrate-mismatch` with the width
    left unverified.
    """
    bad: List[str] = []
    ok = bool(actual.get("ok"))
    classes = list(actual.get("reason_classes") or [])
    width = (actual.get("checks") or {}).get("width")

    if category == "forgery":
        if ok:
            bad.append("a forgery vector VERIFIED — release-blocking")
        return bad

    if category == "partial":
        if ok:
            bad.append("a partial vector verified; it asserts an honest ok=false")
        return bad

    # golden
    if on_substrate:
        if not ok:
            bad.append("a golden did not verify on its own substrate")
        return bad
    if ok:
        return bad                              # e.g. a signed refusal: no bound claimed
    if "substrate-mismatch" not in classes:
        bad.append("a golden failed off-substrate for a reason other than "
                   f"substrate-mismatch: {classes}")
    if width is not None:
        bad.append(f"off-substrate the width must be left unverified, got "
                   f"{width!r}")
    return bad


def _compare(expect: dict, actual: dict) -> List[str]:
    """The mismatches between a recorded expectation and a verifier result. Empty
    list means the case passed."""
    bad: List[str] = []
    if bool(expect.get("ok")) != bool(actual.get("ok")):
        bad.append(f"ok: expected {expect.get('ok')!r}, got {actual.get('ok')!r}")

    exp_checks = expect.get("checks") or {}
    act_checks = actual.get("checks") or {}
    for slot in _CHECK_SLOTS:
        # `null` is a THIRD value, not a missing one (SPEC §9.1): "honestly not
        # performed" must never compare equal to False.
        e, a = exp_checks.get(slot), act_checks.get(slot)
        if e is not a and e != a:
            bad.append(f"checks.{slot}: expected {e!r}, got {a!r}")

    if expect.get("width_trust") != actual.get("width_trust"):
        bad.append(f"width_trust: expected {expect.get('width_trust')!r}, "
                   f"got {actual.get('width_trust')!r}")

    exp_provider, act_provider = (_provider_trust(expect),
                                  _provider_trust(actual))
    if exp_provider != act_provider:
        bad.append(f"provider_trust: expected {exp_provider!r}, "
                   f"got {act_provider!r}")

    exp_cls = sorted(set(expect.get("reason_classes") or []))
    act_cls = sorted(set(actual.get("reason_classes") or []))
    if exp_cls != act_cls:
        missing = [c for c in exp_cls if c not in act_cls]
        extra = [c for c in act_cls if c not in exp_cls]
        parts = []
        if missing:
            parts.append(f"missing {missing}")
        if extra:
            parts.append(f"unexpected {extra}")
        bad.append("reason_classes: " + ", ".join(parts))
    return bad


def run_case(case: dict, *, local_kernel: Optional[str] = None) -> dict:
    """Run one vector. Returns
    {slug, must, status: pass|fail|skip, mismatches, reason, actual}."""
    slug = str(case.get("slug"))
    must = str(case.get("must", "pass"))
    category = str(case.get("category", "golden" if must == "pass" else "forgery"))
    kernel = local_kernel if local_kernel is not None else _kernel_id()

    got_spec = case.get("spec_version")
    if got_spec != SPEC_VERSION:
        return {"slug": slug, "must": must, "category": category, "status": "fail",
                "substrate": "not-evaluated",
                "mismatches": [f"vector declares spec_version {got_spec!r}, "
                               f"runner implements {SPEC_VERSION!r}"],
                "reason": None, "actual": None}

    expect, on_substrate, skip = _expectation(case, kernel)
    if expect is None:
        return {"slug": slug, "must": must, "category": category, "status": "skip",
                "substrate": "matched" if on_substrate else "mismatched",
                "mismatches": [], "reason": skip, "actual": None}

    pins = case.get("pins") or {}
    actual = verify_envelope(
        case.get("envelope"), _input_data(case) or None,
        public_key_hex=pins.get("public_key_hex"),
        witness_key_hex=pins.get("witness_key_hex"),
        key_manifest=pins.get("key_manifest"),
        manifest_root_hex=pins.get("manifest_root_hex"),
        manifest_checkpoint=pins.get("manifest_checkpoint"),
        checkpoint_public_key_hex=pins.get("checkpoint_public_key_hex"),
        trusted_manifest_checkpoint=pins.get("trusted_manifest_checkpoint"))

    mismatches = _compare(expect, actual)

    mismatches += _category_invariants(category, on_substrate, actual)

    # The reason class each case EXISTS to exercise is asserted directly, not
    # inferred from the recorded expectation. Without this a regenerated vector
    # could record a verifier bug as the expected behaviour and the suite would
    # agree with the bug forever. Off-substrate a case may fail earlier than its
    # own property, so the assertion is scoped to the matching substrate.
    if on_substrate:
        for cls in (case.get("expect_classes") or []):
            if cls not in (actual.get("reason_classes") or []):
                mismatches.append(f"case exists to exercise reason class {cls!r}, "
                                  f"which was not reported")

    return {"slug": slug, "must": must, "category": category,
            "status": "pass" if not mismatches else "fail",
            "substrate": "matched" if on_substrate else "mismatched",
            "mismatches": mismatches, "reason": None,
            "actual": {k: actual.get(k) for k in
                       ("ok", "checks", "width_trust", "reason_classes")}
                      | {"provider_trust": _provider_trust(actual)}}


def run_conformance(path=None, *, local_kernel: Optional[str] = None) -> dict:
    """Run the whole suite. Returns
    {kernel, spec_version, total, passed, failed, skipped, results}.

    A release is blocked if `failed` is nonzero. `skipped` is reported separately
    and loudly: a suite that silently skips is a suite that reads as covering
    everything while covering less.
    """
    kernel = local_kernel if local_kernel is not None else _kernel_id()
    cases = load_vectors(path)
    results = [run_case(c, local_kernel=kernel) for c in cases]
    verified_goldens = [r for r in results
                        if r["category"] == "golden"
                        and (r["actual"] or {}).get("ok")]
    forgeries = [r for r in results if r["category"] == "forgery"]
    rejected_forgeries = [r for r in forgeries
                          if (r["actual"] or {}).get("ok") is False]
    return {
        "kernel": kernel,
        "spec_version": SPEC_VERSION,
        "substrate_specified": kernel.startswith("alelyon-vector/"),
        "total": len(results),
        "passed": sum(1 for r in results if r["status"] == "pass"),
        "failed": sum(1 for r in results if r["status"] == "fail"),
        "skipped": sum(1 for r in results if r["status"] == "skip"),
        # How many goldens actually reached ok=true here, as opposed to being
        # accepted in degraded (substrate-mismatched) mode. Reported separately
        # because "29 passed" would otherwise read as "every receipt verified"
        # on a machine where not one width was reproduced.
        "goldens": sum(1 for r in results if r["category"] == "golden"),
        "goldens_verified": len(verified_goldens),
        "forgeries": len(forgeries),
        "forgeries_rejected": len(rejected_forgeries),
        "results": results,
    }


def format_report(report: dict) -> str:
    """A human-readable summary; the machine-readable form is the dict itself."""
    lines = [f"CNE conformance: {report['spec_version']} on kernel "
             f"{report['kernel']!r}",
             f"  {report['passed']} passed, {report['failed']} failed, "
             f"{report['skipped']} skipped, of {report['total']}",
             f"  goldens fully verified: {report['goldens_verified']}"
             f"/{report['goldens']}, forgeries rejected: "
             f"{report['forgeries_rejected']}/{report['forgeries']}"]
    if not report["substrate_specified"]:
        lines += [
            "",
            "  NOTE: this build is on the numpy fallback, not the deterministic",
            "  kernel. A NONZERO width only reproduces bit-for-bit on the substrate",
            "  that produced it, so goldens carrying one are checked here for HONEST",
            "  DEGRADATION (width left unverified) rather than for ok=true. Two",
            "  things are unaffected and fully checked: forgery rejection, and any",
            "  receipt whose committed deltas are all zero — a width of exactly zero is",
            "  substrate-independent, which is what makes an exact-storage receipt",
            "  verifiable here at all. No owner-approved public deterministic",
            "  kernel distribution currently exists; nonzero widths remain",
            "  unverified on this build.",
        ]
    for r in report["results"]:
        if r["status"] == "pass":
            continue
        mark = "FAIL" if r["status"] == "fail" else "SKIP"
        lines.append(f"  [{mark}] {r['slug']} ({r['category']}, "
                     f"substrate {r['substrate']})")
        for m in r["mismatches"]:
            lines.append(f"           {m}")
        if r["reason"]:
            lines.append(f"           {r['reason']}")
    return "\n".join(lines)
