"""The Certified Answer Engine — verified, decision-grade natural-language analytics.

    from alelyon.runtime.oracle.answer import answer, ollama_llm
    va = answer("3-month correlation of SPY and TLT", data_service=ds, llm_fn=ollama_llm())
    # va.value (computed by the interpreter, not the LLM), va.dsl, va.sources,
    # va.certificate (calibrated interval), or va.refused=True with va.error.

The number is COMPUTED and CERTIFIED, never generated by the model — the model's
only output channel is a safe DSL program. Un-productized triad nobody ships:
LLM-can-only-emit-DSL + deterministic PIT execution + calibrated attributable bar.
"""
from __future__ import annotations

from alelyon.runtime.oracle.answer.engine import (
    Certificate, VerifiedAnswer, answer, build_prompt, certify, clean_dsl,
    grammar, sources_of,
)
from alelyon.runtime.oracle.answer.providers import ollama_llm

__all__ = [
    "answer", "VerifiedAnswer", "Certificate",
    "build_prompt", "grammar", "clean_dsl", "sources_of", "certify",
    "ollama_llm",
]
